### ISSUE TITLE
Blender v-3.0 not working

### ISSUE THREAD

**Issue by Brotherarchii** [artempoletsky/blender_1_click_rig#1]
Blender v-3.0 not working.

**Comment by MK-HATERS** [comment]
same here

**Comment by Qworc** [comment]
Blender 3.0 removed chardet so the plugin is broken for it atm

**Comment by Rock0404** [comment]
chardet 4.0.0 → charset_normalizer 2.0.6 (working)

**Comment by artempoletsky** [comment]
> chardet 

I don't know how it got there. It hadn't even needed, lol. 


Fixed in the release:
https://github.com/artempoletsky/blender_1_click_rig/releases/tag/v1.4.5
